## 2.4版本后，外部文件始终会覆盖打包的文件，之前不会覆盖

spring:
  profiles:
    active: dev
#  config:
#    activate:
#      on-profile: node2
server:
  undertow:
    accesslog:
      enabled: true
      dir: logs/undertow
    url-charset: UTF-8
    max-http-post-size: -1B
    threads:
      io: 8
      worker: 64
management:
  endpoints: 
    web:
      base-path: /manage
      exposure:
        include:  
        - "*"
  endpoint: 
    health:
      show-details: always
---
spring:
  profiles:
    group: 
      node1: redis
#  config:
#    activate:
#      on-profile: node2
server:
  port: 8101
hello:
  msg: '[当前节点 node1] 你好，'
  host: 192.168.1.2
  port: 8289
  
---
spring:
  config:
    activate:
      on-profile: node2
server:
  port: 8102
hello:
  msg: '[当前节点 node2] 你好，'
  host: 192.168.1.2
  port: 8289
  
---
spring:
  config:
    activate:
      on-profile: node3
server:
  port: 8103
hello:
  msg: '[当前节点 node3] 你好，'
  host: 192.168.1.2
  port: 8289
