spring:
  profiles:
    active: ${config.profile:dev}
---
spring:
  profiles: node1
server:
  port: 8101
hello:
  msg: '[当前节点 node1] 你好，'
  host: 192.168.1.2
  port: 8289
---
spring:
  profiles: node2
server:
  port: 8102
hello:
  msg: '[当前节点 node2] 你好，'
  
---
spring:
  profiles: node3
server:
  port: 8103
hello:
  msg: '[当前节点 node3] 你好，'
