## 2.4版本后，外部文件始终会覆盖打包的文件，之前不会覆盖

spring:
  profiles:
    active: dev
#  config:
#    activate:
#      on-profile: node2
server:
  undertow:
    accesslog:
      enabled: true
      dir: logs/undertow
    url-charset: UTF-8
    max-http-post-size: -1B
    ## Undertow 线程和连接管理
    threads:
      io: 8               ## cpu数量
      worker: 256          ## 默认IO线程数*8
    buffer-size: 1024     ## 默认：1024 字节
    direct-buffers: false ## 虽然直接内存的性能通常优于堆内存，但它对系统的资源消耗更高。因此，对于资源受限的环境或不处理大文件上传、下载的场景，可以将 directBuffers 设置为 false，让 Undertow 使用堆内存来管理网络连接的缓冲区。
  ## Tomcat 线程和连接管理
  tomcat:
    threads:
      min-spare: 25 ## 默认：10
      max: 300  ## 默认：200
    accept-count: 100
    max-connections: 8192
management:
  endpoints: 
    web:
      base-path: /manage
      exposure:
        include:  
        - "*"
  endpoint: 
    health:
      show-details: always
---
spring:
  profiles:
    group: 
      node1: redis
#  config:
#    activate:
#      on-profile: node2
server:
  port: 8101
hello:
  msg: '[当前节点 node1] 你好，'
  host: 192.168.1.2
  port: 8289
  
---
spring:
  config:
    activate:
      on-profile: node2
server:
  port: 8102
hello:
  msg: '[当前节点 node2] 你好，'
  host: 192.168.1.2
  port: 8289
  
---
spring:
  config:
    activate:
      on-profile: node3
server:
  port: 8103
hello:
  msg: '[当前节点 node3] 你好，'
  host: 192.168.1.2
  port: 8289
