spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/springboot-mongo-upload
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

hello:
  msg: 使用mongoDB存储上传文件
        
        
      