spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:53306/test-mysql8?useUnicode=true&characterEncoding=UTF-8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: iamdante
    