create table t_user (
	id bigint generated by default as identity (start with 1),
	name varchar(64) not null,
	age int not null,
	primary key(id)
);

create table t_contact (
	id bigint generated by default as identity (start with 10),
	user_id bigint,
	mobile varchar(20) not null,
	address varchar(512),
	constraint fk_user_contact foreign key(user_id) references t_user(id) on delete cascade,
);