## If you use the Mongo 3.0 Java driver, spring.data.mongodb.host and spring.data.mongodb.port are not supported. 
## In such cases, spring.data.mongodb.uri should be used to provide all of the configuration.

spring:
  data:
    mongodb:
#      database: springboot
#      uri: mongodb://127.0.0.1:27017
#      username: root
#      password: iamdante
      uri: mongodb://root:iamdante@127.0.0.1:27017/springboot
#      authentication-database: springboot
      
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    