## If you use the Mongo 3.0 Java driver, spring.data.mongodb.host and spring.data.mongodb.port are not supported. 
## In such cases, spring.data.mongodb.uri should be used to provide all of the configuration.

spring:
  data:
    mongodb:
      uri: mongodb://root:iamdante@localhost:27017/springboot
      authentication-database: admin    
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG