spring:
  application:
    name: springboot_admin_client
  boot:
    admin:
      client:
        username: dante
        password: 123456
        url: http://localhost:8900
        instance:
          service-base-url: http://localhost:8900
#        prefer-ip: true
          metadata:
            user.name: dante
            user.password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS