server:
  port: 8101
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/springboot_mybatis_flex
    username: root
    password: iamdante
    
mybatis-flex:
  datasource:
    ds1:
      url: jdbc:mysql://localhost:3307/springboot_mybatis_flex
      username: root
      password: iamdante
    ds2:
      url: jdbc:mysql://localhost:3307/springboot_mybatis_flex2
      username: root
      password: iamdante