server:
  port: 8101
sms:
  config-type: yaml
  blends:
    aliyunsms:  # configId
      supplier: alibaba # 短信供应商
      access-key-id: 您的accessKey
      access-key-secret: 您的accessKeySecret
      signature: 测试签名
      template-id: 模板ID 非必须配置，如果使用sendMessage的快速发送需此配置
      sdk-app-id: 您的sdkAppId
      proxy:
        # 是否启用代理 默认关闭 需手动开启
        enable: false
        host: 127.0.0.1
        port: 8080
    huawei-sms:  # configId
      supplier: huawei # 短信供应商
      access-key-id: 您的accessKey
      access-key-secret: 您的accessKeySecret
      signature: 测试签名
      template-id: 模板ID 非必须配置，如果使用sendMessage的快速发送需此配置
      sdk-app-id: 您的sdkAppId
      proxy:
        # 是否启用代理 默认关闭 需手动开启
        enable: false
        host: 127.0.0.1
        port: 8080
