server:
  port: 8801
spring: 
  datasource: 
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:config.yaml
mybatis: 
  mapper-locations: classpath*:mappers/*Mapper.xml