spring:
  datasource:
    ds-0: 
      hikari:
        jdbc-url: jdbc:mysql://localhost/ds_0?characterEncoding=utf8&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: iamdante
        pool-name: Spirit-ds0-HikariCP
        maximum-pool-size: 25 # 连接池中连接的最大数 = 使用中 + 空闲的。默认值 10。
        auto-commit: true # 默认 false
        connection-timeout: 30000 # 等待池中连接的最大毫秒数，没有连接可用并等待超过这个时间，会抛出SQLException。默认 30秒，不得小于 250毫秒。
        minimum-idle: 10 # 最少空闲连接数，默认 = maximumPoolSize。（官方建议不设置此值）
        idle-timeout: 60000 # 连接在池中空闲的最长时间，minimumIdle < maximumPoolSize 时适用，默认 600000（10分钟），0 表示永远不会从池中删除空闲连接，最小值 10秒
        max-lifetime: 1800000 # 连接生命时长，比mysql的wait_timeout短1分钟左右。推荐设置，0 表示无限生命周期，默认 1800000（30分钟）
    ds-1:  
      hikari:
        jdbc-url: jdbc:mysql://localhost/ds_1?characterEncoding=utf8&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: iamdante
        pool-name: Spirit-ds1-HikariCP
        maximum-pool-size: 25 # 连接池中连接的最大数 = 使用中 + 空闲的。默认值 10。
        auto-commit: true # 默认 false
        connection-timeout: 30000 # 等待池中连接的最大毫秒数，没有连接可用并等待超过这个时间，会抛出SQLException。默认 30秒，不得小于 250毫秒。
        minimum-idle: 10 # 最少空闲连接数，默认 = maximumPoolSize。（官方建议不设置此值）
        idle-timeout: 60000 # 连接在池中空闲的最长时间，minimumIdle < maximumPoolSize 时适用，默认 600000（10分钟），0 表示永远不会从池中删除空闲连接，最小值 10秒
        max-lifetime: 1800000 # 连接生命时长，比mysql的wait_timeout短1分钟左右。推荐设置，0 表示无限生命周期，默认 1800000（30分钟）
