## HikariCP 数据源连接池配置。https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
## 建议设置 maxLifetime、maximumPoolSize、connectionTimeout，其余配置默认
server:
  port: 8100
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost/springboot_flowable?characterEncoding=utf8&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: iamdante
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: Spirit-HikariCP
      maximum-pool-size: 25 # 连接池中连接的最大数 = 使用中 + 空闲的。默认值 10。
      auto-commit: true # 默认 false
      connection-timeout: 30000 # 等待池中连接的最大毫秒数，没有连接可用并等待超过这个时间，会抛出SQLException。默认 30秒，不得小于 250毫秒。
      minimum-idle: 10 # 最少空闲连接数，默认 = maximumPoolSize。（官方建议不设置此值）
      idle-timeout: 60000 # 连接在池中空闲的最长时间，minimumIdle < maximumPoolSize 时适用，默认 600000（10分钟），0 表示永远不会从池中删除空闲连接，最小值 10秒
      max-lifetime: 1800000 # 连接生命时长，比mysql的wait_timeout短1分钟左右。推荐设置，0 表示无限生命周期，默认 1800000（30分钟）
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: org.dante.springboot.mybatis.vo
flowable:
  activityFontName: 宋体
  labelFontName: 宋体
  annotationFontName: 宋体
logging.level.org.flowable.ui.modeler.domain.Model: error