spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/springbatch
    username: root
    password: iamdante
  batch:
    initializer:
      enabled: true