server:
  port: 8199
spring:
  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        min-idle: 10
        max-idle: 50
        max-active: 200
        max-wait: 3000
    cluster:
      nodes:
      - 127.0.0.1:7000
      - 127.0.0.1:7001
      - 127.0.0.1:7002
      - 127.0.0.1:7003
      - 127.0.0.1:7004
      - 127.0.0.1:7005  
      max-redirects: 3
  sql:
    init:
      platform: h2
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: info