spring:
  redis:
    database: 1
    host: localhost
    password: null
    port: 6379
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
      max-wait: 1
  datasource:
    platform: h2
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: info