drop table t_user if exists;
create table t_user (
	id bigint generated by default as identity,
	user_name varchar(32) not null,
	password varchar(256) not null,
	email varchar(256) not null,
	last_password_reset_date timestamp not null,
	primary key(id)
);

drop table t_role if exists;
create table t_role (
	id bigint generated by default as identity,
	code varchar(32) not null,
	name varchar(32) not null,
	primary key(id)
);

drop table t_user_role if exists;
create table t_user_role (
	id bigint not null auto_increment,
	user_id bigint not null,
	role_id bigint not null,
	primary key(id)
);