spring:
  application:
    name: dante-springboot-mybatis
  sql:
    init:
      platform: h2
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql
server:
  port: 8100
mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: org.dante.springboot.po
  type-handlers-package: org.dante.springboot.handler
logging:
  level:
    root: info
    org.dante.springboot.dao: DEBUG
    org.dante.springboot.plugin.SqlCostInterceptor: DEBUG