spring:
  application:
    name: dante-springboot-mybatis
  datasource:
    platform: h2
server:
  port: 8100
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: org.dante.springboot.po
logging:
  level:
    org.dante.springboot.dao: DEBUG
    