drop table t_student if exists;
create table t_student (
	id bigint generated by default as identity,
	name varchar(32) not null,
	age int not null,
	update_date timestamp not null,
	primary key(id)
);

drop table t_student_address if exists;
create table t_student_address (
	id bigint not null auto_increment,
	province varchar(32) not null,
	city varchar(32) not null,
	area varchar(32) not null,
	street varchar(128) not null,
	student_id bigint not null,
	primary key(id)
);

drop table t_teacher if exists;
create table t_teacher (
	id bigint generated by default as identity,
	name varchar(32) not null,
	post varchar(32) not null,
	update_date timestamp not null,
	primary key(id)
);

drop table t_course if exists;
create table t_course (
	id bigint generated by default as identity,
	name varchar(32) not null,
	week varchar(4) not null,
	start_time varchar(4) not null,
	end_time varchar(4) null,
	primary key(id)
);

drop table t_student_course if exists;
create table t_student_course (
	id bigint not null auto_increment,
	student_id bigint not null,
	course_id bigint not null,
	primary key(id)
);

drop table t_teacher_course if exists;
create table t_teacher_course (
	id bigint not null auto_increment,
	teacher_id bigint not null,
	course_id bigint not null,
	primary key(id)
);
