spring:
  application:
    name: dante-springboot-logger
  profiles:
    active: dev
server:
  port: 8101
  
---
## 管理端口
management:
  server:
    port: 10000
    servlet:
      context-path: /adminmanage
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      path-mapping:
        shutdown: /logger_shutdown ## 关闭服务，curl -X POST http://localhost:10000/adminmanage/logger_shutdown

---
spirit:
  name: SpiritProp
  aliPay:
    appId: 2016011401091406