debug: false
sec:
  kaptcha: true
  ldap:
    url: ldap://10.72.8.10:389/
server:
  port: 8888
  context-path: /sec
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/springsecurity
    username: root
    password: iamdante
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: false
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: info