server:
  port: 9001
spring:
  thymeleaf:
    cache: false

sa-token:
  sso:
    # SSO-Server端-单点登录授权地址 
    auth-url: http://x.dante.com:9000/sso/auth
    # 是否打开单点注销接口
    is-slo: true
  alone-redis: 
    # Redis数据库索引
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 
    # 连接超时时间
    timeout: 10s