spring:
  sql:
    init:
      platform: h2
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql
  datasource: 
    platform: h2
  thymeleaf:
    cache: false
    mode: HTML
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: info  