spring:
  datasource:
    platform: h2
  thymeleaf:
    cache: false
    mode: HTML
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: info  