server:
  port: 8101
spring:
  sql:
    init:
      platform: h2
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false