server:
  port: 8101
spring:
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false