INSERT  INTO
	jimu_report_db_param
      ( 
      ID                            
      ,JIMU_REPORT_HEAD_ID            
      ,PARAM_NAME                     
      ,PARAM_TXT                      
      ,PARAM_VALUE                    
      ,ORDER_NUM                      
      ,CREATE_BY                      
      ,CREATE_TIME                    
      ,UPDATE_BY                      
      ,UPDATE_TIME
      ,SEARCH_FLAG
      ,SEARCH_MODE
      ,WIDGET_TYPE
      ,DICT_CODE
      ,SEARCH_FORMAT
      ,EXT_JSON
      ) 
values
      (
      :jimuReportDbParam.id                            
      ,:jimuReportDbParam.jimuReportHeadId              
      ,:jimuReportDbParam.paramName                     
      ,:jimuReportDbParam.paramTxt                      
      ,:jimuReportDbParam.paramValue                    
      ,:jimuReportDbParam.orderNum                      
      ,:jimuReportDbParam.createBy                      
      ,:jimuReportDbParam.createTime                    
      ,:jimuReportDbParam.updateBy                      
      ,:jimuReportDbParam.updateTime
      ,:jimuReportDbParam.searchFlag
      ,:jimuReportDbParam.searchMode
      ,:jimuReportDbParam.widgetType
      ,:jimuReportDbParam.dictCode
      ,:jimuReportDbParam.searchFormat
      ,:jimuReportDbParam.extJson
      )