spring:
  redis:
    jedis:
      pool:
        min-idle: 10     # 连接池中的最小空闲连接
        max-idle: 50     # 连接池中的最大空闲连接
        max-active: 200  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
    cluster:
      nodes:
      - 127.0.0.1:31000
#      - 127.0.0.1:7000
#      - 127.0.0.1:7001
#      - 127.0.0.1:7002
#      - 127.0.0.1:7003
#      - 127.0.0.1:7004
#      - 127.0.0.1:7005  
      max-redirects: 3  # 获取失败 最大重定向次数