spring:
  redis:
    host: 127.0.0.1
    pool:
      min-idle: 10
      max-idle: 50
      max-active: 200
      max-wait: 3000
    cluster:
      nodes:
      - 127.0.0.1:7000
      - 127.0.0.1:7001
      - 127.0.0.1:7002
      - 127.0.0.1:7003
      - 127.0.0.1:7004
      - 127.0.0.1:7005  
      max-redirects: 3