truncate act_hi_actinst;
truncate act_hi_attachment;
truncate act_hi_comment;
truncate act_hi_detail;
truncate act_hi_identitylink;
truncate act_hi_procinst;
truncate act_hi_taskinst;
truncate act_hi_varinst;
truncate act_ru_variable;
truncate act_ru_identitylink;
delete from act_ru_task;
delete from act_ru_execution;