# 该文件配置会继承bootstrap.xml，只需要配置数据库等差异配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_aj_report?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: iamdante
  gaea:
    subscribes:
      oss: #文件存储
        enabled: true
        ##允许上传的文件后缀
        file-type-while-list: .png|.jpg|.gif|.icon|.pdf|.xlsx|.xls|.csv|.mp4|.avi|.jpeg
        # 用于文件上传成功后，生成文件的下载公网完整URL
        downloadPath: http://127.0.0.1:9095/file/download
        nfs:
          path: /Users/dante/Documents/Project/java-world/springboot/springboot-aj-report/nfs





