spring:
  profiles:
    active: ${config.profile:svc1}
opentracing:
  jaeger:
    udp-sender:
      host: 127.0.0.1
      port: 6831
    probabilistic-sampler:
      sampling-rate: 0.8
    rate-limiting-sampler:
      max-traces-per-second: 0.6