hello:
  msg: 'Service 3'
  sleep: 1
server:
  port: 8803
spring:
  application:
    name: svc3
opentracing:
  jaeger:
    udp-sender:
      host: 127.0.0.1
      port: 5775
    probabilistic-sampler:
      sampling-rate: 0.8
    rate-limiting-sampler:
      max-traces-per-second: 0.6