server:
  port: 8100
spring:
  application:
    name: springboot-postgresql
  datasource: 
    url: jdbc:postgresql://localhost:5432/test?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: iamdante
  sql:
    init:
      platform: postgresql
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always
mybatis-plus:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  type-aliases-package: org.dante.springboot.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl