server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  flyway:
    baseline-version: 1
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"