server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/springboot_flyway?characterEncoding=utf8&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: iamdante
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: true
    baseline-on-migrate: true 