server:
  port: 8900
spring:
  application:
    name: sba_server
  security:
    user:
      name: dante
      password: 123456      
          
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
        
      