spring:
  mail:
    host: smtp.163.com
    username: sunchao.0129@163.com
    password: Springboot163
    default-encoding: UTF-8
    protocol: smtp
    properties:
      smtp:
        auth: true
        starttls: 
          enable: true
          required: true
spirit:
  email: 
    from: sunchao.0129@163.com