spring:
  mail:
    host: smtp.163.com
    username: "sunchao.0129@163.com"
    password: NWSONKUQNOKZFRRB
    default-encoding: UTF-8
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls: 
            enable: true
            required: true