INSERT  INTO
	jimu_report_db_field
      ( 
      ID                            
      ,CREATE_BY                      
      ,CREATE_TIME                    
      ,UPDATE_BY                      
      ,UPDATE_TIME                    
      ,JIMU_REPORT_DB_ID              
      ,FIELD_NAME                     
      ,FIELD_TEXT                     
      ,WIDGET_TYPE                    
      ,WIDGET_WIDTH                   
      ,ORDER_NUM                      
      ,SEARCH_FLAG                    
      ,SEARCH_MODE                    
      ,DICT_CODE
      ,SEARCH_VALUE
      ,SEARCH_FORMAT
      ,EXT_JSON
      ) 
values
      (
      :jimuReportDbField.id                            
      ,:jimuReportDbField.createBy                      
      ,:jimuReportDbField.createTime                    
      ,:jimuReportDbField.updateBy                      
      ,:jimuReportDbField.updateTime                    
      ,:jimuReportDbField.jimuReportDbId                
      ,:jimuReportDbField.fieldName                     
      ,:jimuReportDbField.fieldText                     
      ,:jimuReportDbField.widgetType                    
      ,:jimuReportDbField.widgetWidth                   
      ,:jimuReportDbField.orderNum                      
      ,:jimuReportDbField.searchFlag                    
      ,:jimuReportDbField.searchMode                    
      ,:jimuReportDbField.dictCode
      ,:jimuReportDbField.searchValue
      ,:jimuReportDbField.searchFormat
      ,:jimuReportDbField.extJson
      )