INSERT  INTO
	jimu_report_db
      ( 
      ID                            
      ,JIMU_REPORT_ID                 
      ,CREATE_BY                      
      ,UPDATE_BY                      
      ,CREATE_TIME                    
      ,UPDATE_TIME                    
      ,DB_CODE                        
      ,DB_CH_NAME                     
      ,DB_TYPE                        
      ,DB_TABLE_NAME                  
      ,DB_DYN_SQL                     
      ,DB_KEY                         
      ,TB_DB_KEY                      
      ,TB_DB_TABLE_NAME               
      ,JAVA_TYPE                      
      ,JAVA_VALUE                     
      ,API_URL                        
      ,API_METHOD                     
      ,IS_PAGE                        
      ,DB_SOURCE                      
      ,DB_SOURCE_TYPE                 
      ,IS_LIST                        
      ,JSON_DATA
      ,API_CONVERT    
      ) 
values
      (
      :jimuReportDb.id                            
      ,:jimuReportDb.jimuReportId                  
      ,:jimuReportDb.createBy                      
      ,:jimuReportDb.updateBy                      
      ,:jimuReportDb.createTime                    
      ,:jimuReportDb.updateTime                    
      ,:jimuReportDb.dbCode                        
      ,:jimuReportDb.dbChName                      
      ,:jimuReportDb.dbType                        
      ,:jimuReportDb.dbTableName                   
      ,:jimuReportDb.dbDynSql                      
      ,:jimuReportDb.dbKey                         
      ,:jimuReportDb.tbDbKey                       
      ,:jimuReportDb.tbDbTableName                 
      ,:jimuReportDb.javaType                      
      ,:jimuReportDb.javaValue                     
      ,:jimuReportDb.apiUrl                        
      ,:jimuReportDb.apiMethod                     
      ,:jimuReportDb.isPage                        
      ,:jimuReportDb.dbSource                      
      ,:jimuReportDb.dbSourceType                  
      ,:jimuReportDb.isList                        
      ,:jimuReportDb.jsonData                     
      ,:jimuReportDb.apiConvert                     
      )