INSERT  INTO
	jimu_report_data_source
      ( 
      ID                            
      ,NAME                           
      ,REPORT_ID                      
      ,CODE                           
      ,REMARK                         
      ,DB_TYPE                        
      ,DB_DRIVER                      
      ,DB_URL                         
      ,DB_USERNAME                    
      ,DB_PASSWORD                    
      ,CREATE_BY                      
      ,CREATE_TIME                    
      ,UPDATE_BY                      
      ,UPDATE_TIME
      ,CONNECT_TIMES
      ,TENANT_ID
      ,TYPE 
      ) 
values
      (
      :jimuReportDataSource.id                            
      ,:jimuReportDataSource.name                          
      ,:jimuReportDataSource.reportId                      
      ,:jimuReportDataSource.code                          
      ,:jimuReportDataSource.remark                        
      ,:jimuReportDataSource.dbType                        
      ,:jimuReportDataSource.dbDriver                      
      ,:jimuReportDataSource.dbUrl                         
      ,:jimuReportDataSource.dbUsername                    
      ,:jimuReportDataSource.dbPassword                    
      ,:jimuReportDataSource.createBy                      
      ,:jimuReportDataSource.createTime                    
      ,:jimuReportDataSource.updateBy                      
      ,:jimuReportDataSource.updateTime
      ,:jimuReportDataSource.connectTimes
      ,:jimuReportDataSource.tenantId
       ,:jimuReportDataSource.type
      )