INSERT  INTO
    jimu_dict_item
      ( 
      ID                            
      ,DICT_ID                        
      ,ITEM_TEXT                      
      ,ITEM_VALUE                     
      ,DESCRIPTION                    
      ,SORT_ORDER                     
      ,STATUS                         
      ,CREATE_BY                      
      ,CREATE_TIME                    
      ,UPDATE_BY                      
      ,UPDATE_TIME                    
      ) 
values
      (
      :dictItem.id                            
      ,:dictItem.dictId                        
      ,:dictItem.itemText                      
      ,:dictItem.itemValue                     
      ,:dictItem.description                   
      ,:dictItem.sortOrder                     
      ,:dictItem.status                        
      ,:dictItem.createBy                      
      ,:dictItem.createTime                    
      ,:dictItem.updateBy                      
      ,:dictItem.updateTime                    
      )