INSERT  INTO
	jimu_report
      ( 
      ID                            
      ,CODE                           
      ,NAME                           
      ,NOTE                           
      ,STATUS                         
      ,TYPE                           
      ,JSON_STR                       
      ,API_URL                        
      ,THUMB                          
      ,CREATE_BY                      
      ,CREATE_TIME                    
      ,UPDATE_BY                      
      ,UPDATE_TIME                    
      ,DEL_FLAG                       
      ,API_METHOD                     
      ,API_CODE                       
      ,TEMPLATE                       
      ,VIEW_COUNT
      ,CSS_STR
      ,JS_STR
      ,TENANT_ID
      ) 
values
      (
      :jimuReport.id                            
      ,:jimuReport.code                          
      ,:jimuReport.name                          
      ,:jimuReport.note                          
      ,:jimuReport.status                        
      ,:jimuReport.type                          
      ,:jimuReport.jsonStr                       
      ,:jimuReport.apiUrl                        
      ,:jimuReport.thumb                         
      ,:jimuReport.createBy                      
      ,:jimuReport.createTime                    
      ,:jimuReport.updateBy                      
      ,:jimuReport.updateTime                    
      ,:jimuReport.delFlag                       
      ,:jimuReport.apiMethod                     
      ,:jimuReport.apiCode                       
      ,:jimuReport.template                      
      ,:jimuReport.viewCount
      ,:jimuReport.cssStr
      ,:jimuReport.jsStr
      ,:jimuReport.tenantId
      )