spring:
  kafka:
    bootstrap-servers:
#     - 172.20.10.2:30092
    - 172.20.10.2:30092
    - 172.20.10.2:30192
    - 172.20.10.2:30292
    consumer:
      group-id: 0
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.dante.springboot.kafka.vo"