spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost/springboot?characterEncoding=utf8&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: iamdante
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver ## com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: select 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      db-type: mysql
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          db-type: mysql
          config:
            multi-statement-allow: true
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        login-username: druid
        login-password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: org.dante.springboot.**.po
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

  