server:
  port: 8101
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
        
  
dromara:
  x-file-storage:
    default-platform: local-plus-1                # 默认本地平台 
    local-plus:                                   # 本地存储
    - platform: local-plus-1                      # 存储平台标识
      enable-storage: true                        # 启用存储
      enable-access: true                         # 启用访问（线上请使用 Nginx 配置，效率更高）
      domain: "http://127.0.0.1:8101/" # 访问域名，例如：“http://127.0.0.1:8101/local-plus/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
      base-path: local-plus/                      # 基础路径
      path-patterns: /local-plus/**               # 访问路径
      storage-path: /Users/dante/Documents/Project/java-world/springboot/springboot-x-file-storage/files/ # 存储路径
      
      
